name: Deploy UptimeRobot

on:
  push:
    branches:
      - master # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }}
            git pull origin master
            npm install
            npx prisma generate
            npx prisma db push
            npm run build
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save
